drop table if EXISTS admin_user;
drop table if EXISTS captions;
drop table if EXISTS media;
drop table if EXISTS cases;

create table if not exists admin_user(
    admin_id serial primary key,
    name varchar(20),
    auth_id text
);



create table if not exists cases(
    case_id serial primary key,
    title varchar(40),
    subtitle varchar(150),
    brand varchar(100),
    blurb varchar(300),
    award_blurb varchar(300),
    deliverables varchar(300),
    link_url varchar(100),
    background_url varchar(100)
);

insert into cases(
 title, subtitle, brand, blurb, award_blurb, deliverables, link_url, background_url
) 
values
('Two locations one museum', 'A platform that reflects the contemporary and classic duality of the museum.', 'Frans Hals Museum', 'Frans Hals Museum and KesselsKramer commissioned us to create a platform that reflects the contemporary and classic duality of the museum.', 'Awwwards Site of the Day, FWA Site of the Day, CSS Design Award', 'Deliverables: Design, development', 'www.franshalmuseum.nl', 'http://www.buildinamsterdam.com/app/uploads/2018/04/Frans-HalsH-KoosBreukelCombi_Zoom.jpg'),
('E-commerce of the Year ‘17', 'Translating the world of Mendo into an e-commerce platform that pushes the standard in online book shopping.', 'Mendo', 'Mendo is a candy store for book aficionados with a flagship store situated in one of the Amsterdam’s most inspirational neighbors, called The 9 Streets (De 9 Straatjes). The store is fully dedicated to sharing the love for beautiful books.', 'Awwward E-commerce Site of the Year 2017, FWA Award, CSS Design Award', 'E-commerce platform', 'www.mendo.nl', 'http://www.buildinamsterdam.com/app/uploads/2017/03/MENDO_Collage_v2.jpg'),
('Sustainable outerware', 'A brand identity translated into a matching e-commerce platform, build to communicate all the aspects of the brand and connects with its community.', 'Open Ware', 'Open Wear is a brand built by - and for - passionate powder riders. They’re out to set a  new transparent standard within the outerwear industry.', 'E-commerce site of the year nominee & Site of the Day on Awwwards, Mindsparkle, Maxi Best-of The Gallery, Siiimple', 'Branding, design & development', 'www.open-wear.com', 'http://www.buildinamsterdam.com/app/uploads/2018/06/123.jpg'),
('Excellence through quality', 'ETQ is not, it`s design', 'ETQ', 'ETQ is all about minimalism. We conveyed this into every single touchpoint, both on and offline.', 'Awwwards, Cssdesign, Siteinspire', 'Branding, Design, Development', 'www.etq-amsterdam.com', 'http://www.buildinamsterdam.com/app/uploads/2018/04/ETQ_Header_Big-1.jpg' ),
('Bringing fragrances to life', 'An e-commerce platform that sparks all senses except smell. For now...', 'Abel vita odor', 'We created an e-commerce platform for Abel fragrances that sparks all senses, except smell.', 'Awwwards Site of the Day, CSSDSGN, thegallery.io', 'Design and technology', 'www.abelodor.com', 'http://www.buildinamsterdam.com/app/uploads/2016/08/abel_cover.jpg'),
('See Buy Fly rebranding', ' Rebranding the touchpoints of the Schiphol Airside Shopping Experience.', 'See Buy Fly', 'Amsterdam Schiphol Airport is one of the best airports in the world and needed an airside shopping experience in tune with this reputation. We rebranded the visual identity for See Buy Fly and translated this into a brand guide.', 'Coming soon...', 'Brand identity, print, photography, art direction, design and development', 'www.seebuyflyhappyhour.nl', 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_cover_1.jpg'),
('Extrodinary world of A-dam', 'A playful e-commerce platform that mirrors the character of the brand.', 'A-dam Underwear', 'Dive into the extraordinary world of A-dam Underwear and discover how we translated their unique brand story into a playful combination of branding and e-commerce.', 'E-commerce site of the year nominee Awwwards, Mindsparkle, Maxi Best-of The Gallery, Siiimple', 'Branding, design & development', 'www.adamunderwear.com', 'http://www.buildinamsterdam.com/app/uploads/2017/07/8.jpg')
;

create table if not exists media(
    media_id serial primary key,
    cases_id integer references cases(case_id) ON DELETE CASCADE,
    media_url varchar (300),
    content varchar (300)
);
insert into media(
    cases_id, media_url, content
)
values
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Franshals_Slideshow.gif', 'Slideshow'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/5_Bottom2-1300x0-c-default.jpg', 'Painting'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Enveloppe.gif', 'Envelope gif'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/FHM-cafe-2000x0-c-default.jpg', 'Cafe pic'),
(1, 'https://player.vimeo.com/video/263126878?api=1&player_id=vjs_video_3_Vimeo_api', 'Video'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Shape-11-1-2500x0-c-default.jpg', 'CellPic'),
(1, 'https://player.vimeo.com/video/263152373?api=1&player_id=vjs_video_677_Vimeo_api', 'Slider Vid'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Screen_1-1500x0-c-default.jpg', 'Iphone1'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Screen_2-1500x0-c-default.jpg ', 'Iphone2'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/Icons_v2-1300x0-c-default.png', 'Icons'),
(1, 'http://www.buildinamsterdam.com/app/uploads/2018/04/manieristenzaal-2500x0-c-default.jpg', 'Museum'),
(1, 'https://player.vimeo.com/video/263154305?api=1&player_id=vjs_video_1559_Vimeo_api', 'Last vid'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/Mendo-1000x800-c-default.gif', 'Shop pic'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/pharell-2500x0-c-default.jpg', 'Laptop'),
(2, 'https://player.vimeo.com/video/210679422?api=1&player_id=vjs_video_1906_Vimeo_api', 'Bookshopping vid'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/Screen-Shot-2017-03-21-at-17.52.11-1500x0-c-default.jpg', 'Phone1'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/iphone_2-1500x0-c-default.jpg', 'Phone 2'),
(2, 'https://player.vimeo.com/video/211350960?api=1&player_id=vjs_video_2788_Vimeo_api', 'Slider vid'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/DSC07410-2500x0-c-default.jpg', 'Solo phone'),
(2, 'https://player.vimeo.com/video/211352119?api=1&player_id=vjs_video_3670_Vimeo_api', 'Fun stuff vid'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/giphy-1.gif', 'gif'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/Kate_2-2000x0-c-default.jpg', 'Model pic'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/MENDO_Collage-1-2500x0-c-default.jpg', 'Books'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/1-800x0-c-default.png', 'Book1'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/aston-800x0-c-default.png', 'Book 2'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/terry-1-800x0-c-default.png', 'Book 3'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/4-800x0-c-default.png', 'Book 4'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/lv-800x0-c-default.png', 'Book 5'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/7-800x0-c-default.png', 'Book 6'),
(2, 'http://www.buildinamsterdam.com/app/uploads/2017/03/download-2.jpg', 'Book'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/123-1.gif', 'Gif'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Devices.jpg', 'Laptop img'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Open-Wear-Kickstarter17-7.jpg', 'Ski img'),
(3, 'https://player.vimeo.com/video/274071268?api=1&player_id=vjs_video_4711_Vimeo_api', 'Main concept vid'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Mock_01-2500x0-c-default.jpg', 'Cell'),
(3, 'https://player.vimeo.com/video/274072517?api=1&player_id=vjs_video_5005_Vimeo_api', 'Vid 2'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Phone_01-1500x0-c-default.jpg', 'Cell 1'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/12-1500x0-c-default.jpg', 'Cell 2'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Factory-2500x0-c-default.jpg', 'Workers'),
(3, 'https://player.vimeo.com/video/274073034?api=1&player_id=vjs_video_5299_Vimeo_api', 'Vid 3'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/iPad-2500x0-c-default.jpg', 'Tablet'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/123-1-1500x0-c-default.jpg', 'Jacket pic'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/logos.jpg', 'Outerware'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/Dopos.jpg', 'Openware'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/small.jpg', 'Openware Pic'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/big.jpg', 'Skier Pic'),
(3, 'http://www.buildinamsterdam.com/app/uploads/2018/06/factory-2500x0-c-default.jpg', 'Worker Pic'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/etq_product-2500x0-c-default.jpg', 'Shoes'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/identity_thumb-1000x800-c-default.jpg', 'Stairs'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2018/04/unnamed-file-1300x0-c-default.png', 'ETQ'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/tablet_mockup-2500x0-c-default.jpg', 'Tablet'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/thumb_bag.jpg', 'Bag1'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/totebag_.jpg', 'Bag2'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/packaging-2500x0-c-default.jpg', 'Whiteshoes'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Photo_Outside.jpg', 'Shop'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/store_interior_2-2500x0-c-default.jpg', 'Store'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Detail1_-1500x0-c-default.jp', 'Stone'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Detail2_-1500x0-c-default.jpg', 'Mac'),
(4, 'https://player.vimeo.com/video/262963039?api=1&player_id=vjs_video_1900_Vimeo_api', 'Shoevid'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2018/04/phone1.jpg', 'Phone1'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2018/04/phone2.jpg', 'Phone2'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Imac-copy-2500x0-c-default.jpg', 'Soloshoe'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Phone_Shot_ETQ-2500x0-c-default.jpg', 'Handphone'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/shoes_girl.jpg', 'Velvet'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Header-02-2000x0-c-default.jpg', 'Coolguy'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/big_shoe-2500x0-c-default.jpg', 'Sneaker'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/outdoors1-1500x0-c-default.jpg', 'Model1'),
(4, 'http://www.buildinamsterdam.com/app/uploads/2015/04/Outdoors2-1500x0-c-default.jpg', 'Model2'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Layer-1-750x600-c-default.jpg', 'Abel'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Abel_logo.png', 'Logo'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Devices-1.jpg', 'Devices'),
(5, 'https://player.vimeo.com/video/263114443?api=1&player_id=vjs_video_2204_Vimeo_api', 'Vid'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Phone1-1500x0-c-default.jpg', 'Phone1'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Phone2-1500x0-c-default.jpg', 'Phone2'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/abel_imac-e1522768552123-2500x0-c-default.jpg', 'Desktop'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/abel-photography.jpg', 'Perfume'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/collage.jpg', 'Collage'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/full-width.jpg', 'Collage2'),
(5, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Screen-Shot-2016-08-02-at-15.37.10-copy.jpg', 'Marble'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_logo-2.jpg', 'Logo'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/header-1500x0-c-default.jpg', 'Header Font'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/prices-1500x0-c-default.jpg', 'Prices'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/lorem-1500x0-c-default.jpg', 'Body'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/171124_SO-folder_mockup_2.jpg', 'Open Magazine pic'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Layer-2.jpg', 'Mascara/Glasse/Phone pic'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_photo_01.jpg', 'Girl Holding Purses Pic'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_photo_03.jpg', 'Suitcase pic'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/171124_Schiphol-airport_SBF-2500x0-c-defa', 'Public Transport Ad Pic 1'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/171124_Schiphol-airport_SBF_Lightbox_square-2000x0-c-default.jpg', 'Public Transport Ad Pic 2'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_photo_02.jpg', 'Umbrella Girl Pic '),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/171124_Schiphol-parking_Billboard-2000x0-c-default.jpg', 'Billboard Pic'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/SBF_photo_04.jpg', 'Happy Family Pic'),
(6, 'https://player.vimeo.com/video/181057538?api=1&player_id=vjs_video_6478_Vimeo_api', 'Website Video'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/1-1500x0-c-default.jpg', 'iPhone Pic1'),
(6, 'http://www.buildinamsterdam.com/app/uploads/2016/08/Group-92-1500x0-c-default.jpg', 'iPhone Pic2'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/01-1000x800-c-default.jpg', 'Guy on Motorcycle'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Logo.png', 'Logo'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Header-1500x0-c-default.png', 'Heading Font'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Subheader.png', 'Sub-heading Font'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Body-1500x0-c-default.png', 'Body Font'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Image-2500x0-c-default.jpg', 'Skateboarder'),
(7, 'https://player.vimeo.com/video/225432736', 'Concept Video 1'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_1-800x0-c-default.png', 'Navy Blue Briefs'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_2-800x0-c-default.png', 'Rainbow Briefs'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_3-800x0-c-default.png', 'Red Briefs'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_4-1-800x0-c-default.png', 'Triangle Briefs'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_5-800x0-c-default.png', 'Polka Dot Briefs'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Product_6-800x0-c-default.png', 'Off White Briefs'),
(7, 'https://player.vimeo.com/video/225432791', 'Animation Video 2'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Mobile_01-1500x0-c-default.jpg', 'iPhone Photo 1'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/123-1500x0-c-default.jpg', 'iPhone Photo 2'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/Adam-Underwear_2016-10-27_Movember_Tomek-Dersu-Aaron_013-2500x0-c-default.jpg', 'Man with bird pic'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/icons-2000x0-c-default.jpg', 'Icons'),
(7, 'https://player.vimeo.com/video/225432808?api=1&player_id=vjs_video_677_Vimeo_api', 'Loader and Details Video3'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/GIF_3.gif', 'Box Gif'),
(7, 'http://www.buildinamsterdam.com/app/uploads/2017/07/2016-07-03_Box-of-Boxers_Tomek-Dersu-Aaron_001-2000x0-c-default.jpg', 'Lobster Pic');


create table if not exists captions(
    caption_id serial primary key,
    case_id integer references cases(case_id) ON DELETE CASCADE,
    caption_title varchar(100),
    caption_content varchar(1000)
);
insert into captions (case_id, caption_title, caption_content)
values
(1, 'One museum two locations', 'On 29 March 2018, the Frans Hals Museum, with its outstanding collection of Old Masters, ‘marries’ De Hallen Haarlem, the museum for contemporary and modern art in Haarlem.'),
(1, 'Main concept', 'KesselsKramer main concept was to combine the old with the new in a mirror. This concept is the main theme that we used throughout the website.'),
(1, 'The identity', 'The identity has been designed by KesselsKramer. We expanded the visual style in the platform.'),
(1, 'Website', 'The Identity is translated in an online environment.'),
(1, 'Learning playfully', 'The website has a playful touch which makes it usable for every target audience.'),
(1, 'Iconography', 'The website has a playfull touch which makes it usuable for every target audience.'),
(1, 'One seamless experience', 'We created a toolset so the museum can explain their art pieces with fine details.'),
(2, 'Translation', 'We translated the world of Mendo in an e-commerce experience where the visitor can see, read and almost feel the book without touching it.'),
(2, 'Next level books shopping', 'We were able to focus on conversion without compromising the identity & design. For example, all animation effects are based on browsing though real books.'),
(2, 'Optimizing the experience', 'Adding smart elements enhances the seamless process of the shopping experience.'),
(2, 'The Fun stuff', 'We`ve directed a photography style where Mendo can showcase their book catalog in a minimalistic way.'),
(2, 'Photography', 'We`ve directed a photography style where Mendo can showcase their book catalog in a minimalistic way.'),
(2, 'Color', 'Building their e-commerce platform required us to reshape their identity. Mendo`s book catalog is varied, therefore the identity touches all colors of the color spectrum in an off-tone fashion.'),
(3, 'The Brand', 'Started as a kickstarter, Open Wear evolved into a real front runner. We devised a new brand voice — from an updated logo to a new online platform.'),
(3, 'Main Concept', 'The goal was to create a shoppable online community. We did this by using a storytelling approach with products, stories and an Instagram cloud.'),
(3, 'Product', 'No long product descriptions. In this product detail page we show everything in a visual way. Things like the jacket’s multi-functionality, why it is cheaper, and its ethical production.'),
(3, 'Stories', 'This section is entirely dedicated to the community. It stimulates an ongoing conversation with the riders. Active participation earns them discount points for the next purchase.'),
(3, 'By and got the Community', 'Return your product by filling in the unique product code and see the jacket’s entire history. Return it directly or answer more questions to earn discount points.'),
(3, 'Identity', 'Every visual aspect of the website is built upon a strong brand identity that respects all the brand values. We’ve sharpened the logo to express the high quality standards of the brand even better.'),
(3, 'Brand Colors', 'We carefully picked a wide rage of new brand colors to merge the website with the products. Every darker tone works together with a light grey to keep cohesion in the modern style.'),
(3, 'Logo', 'We`ve updated the logo to make it match the qualitative products.'),
(4, 'Identity', 'We combined minimalism and unruliness to create an identity that complements the high-quality, refined products made by ETQ.'),
(4, 'Branding', 'Every single piece of printed communication is crafted to convey the qualitative and paring-down ethos of ETQ.'),
(4, 'Refinement in details', 'The visual language we created for ETQ is extended to all their physical touchpoints. From shoebox to shopping experience.'),
(4, 'E-commerce', 'For the e-commerce platform our focus was to create a top-notch shopping experience, without any frills. Quality over quantity.'),
(4, 'Photography', 'We created several photography styles that all complement each other, using restrained compositions and minimal backgrounds. The ensuing result is balanced, qualitative and never dull.'),
(5, 'Identity', 'We adapted the new identity created by Atelier Joachim Baan to an online use.'),
(5, 'Website', 'We let the photographic moodboards and soundscapes inspire and help the visitors to picture the different scents.'),
(5, 'Photography', 'We invite potential customers to dive into the ambiance of each fragrance by combining products and inspirational images.'),
(5, 'Living Fragrances', 'We introduce the new world of Abel with a lifelike texture randomly animated which the visitor can interact with.'),
(6, 'Logo', 'We refreshed the SBF logo with brighter color and a new flat look, already recognized via the famous bag.'),
(6, 'Header', 'Frutiger LT Std Bold'),
(6, 'Prices', 'DIN Bold'),
(6, 'Body', 'Frutiger LT Std Roman'),
(6, 'Brand colors', 'We established a clear color palette with a dominant yellow and Schiphol blue, along with several pastel tones and a warm gray.'),
(6, 'Products', 'We introduced a systematic way to showcase products. By using a color as a background along with the gray, a horizon is created, allowing the items to be highlighted.'),
(6, 'Photography', 'We wanted the photography to have a lively, open feel. The airside shopping must look accessible and inviting.'),
(6, 'Campaign material', 'Along with the photography we deliver a complete set of guidelines to help create campaign material for See Buy Fly, Schiphol Parking and Plaza.'),
(6, 'Schiphol Parking', 'The new style was progressively extended to Schiphol Parking communications.'),
(6, 'Website', 'We developed an online platform that features and implements on interesting product deals and implemented smart functions like a Wishlist and a reservation service.'),
(7, 'The Brand', 'We enriched their black and white brand identity with a colourful extra layer, fresh icons, and new typo, to create a new, richer identity for both online and offline.'),
(7, 'Heading', 'GT Walsheim Bold'),
(7, 'Sub-heading', 'GT Walsheim Bold'),
(7, 'Body', 'GT Walsheim Regular'),
(7, 'Color', 'We selected five bright shades that match perfectly, and reflect the colourful playfulness of A-dam.'),
(7, 'Concept', 'The idea of the website was to combine storytelling with product imagery, in order to tell the brand story and present the collection in a playful way.'),
(7, 'Animation', 'Animation plays a huge roll in terms of functionality and story telling. It is used for smooth scrolling, seamless page transitions, funny hover states, and other applications.'),
(7, 'Icons', 'We’ve created a set of icons for functional use and to add a playful touch to certain elements.'),
(7, 'Loader and details', 'A few examples of a funny website loader and a functional product detail page.'),
(7, 'More than online', 'We helped A-dam out with packaging and retail ideas.');

